# Generated by Django 5.0.3 on 2024-03-27 19:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nightlif", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlocation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
